# -*- mode: ruby -*-
# vi: set ft=ruby :
{%- from "vagrant/map.jinja" import control with context %}

{%- set cluster = salt['pillar.get']('vagrant:control:cluster:'+cluster_name) %}

boxes = {
  {%- for name, image in control.image.iteritems() %}
  '{{ name }}' => {
    'name'  => '{{ name }}',
    'url'   => '{{ image.source }}'
  },
  {%- endfor %}
}

Vagrant.configure("2") do |config|

  {%- for node_name, node in cluster.node.iteritems() %}
  {%- set node_fqdn = node_name+'.'+cluster.domain %}

  config.vm.define :{{ node_name }} do |{{ node_name }}|

    {{ node_name }}.vm.hostname = '{{ node_fqdn }}'
    {{ node_name }}.vm.box = '{{ node.image }}'
    {{ node_name }}.vm.box_url = boxes['{{ node.image }}']['url']
    {%- if node.networks is defined %}
    {%- for network in node.networks %}
    {%- if network.type == 'hostonly' %}
    {{ node_name }}.vm.network :private_network, ip: "{{ network.address }}"
    {%- endif %}
    {%- if network.type == 'bridged' %}
    {{ node_name }}.vm.network :public_network, :bridge => "{{ network.bridge }}"{% if network.address is defined %}, ip: "{{ network.address }}"{% endif %}
    {%- endif %}
    {%- endfor %}
    {%- endif %}

    {{ node_name }}.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", {{ node.memory }}]
      vb.customize ["modifyvm", :id, "--cpus", {{ node.cpus }}]
      vb.name = '{{ cluster_name }}_{{ node_name }}'
      {%- if node.get('gui', False) %}
      vb.gui = true
      {%- else %}
      vb.gui = false
      {%- endif %}
    end

    {%- if cluster.config.engine == "salt" %}

    {{ node_name }}.vm.provision :salt do |salt|
      salt.run_highstate = true
      salt.minion_config = "/srv/vagrant/{{ cluster_name }}/salt/{{ node_name }}/minion.conf"
      salt.minion_key = "/srv/vagrant/{{ cluster_name }}/salt/minion_keys/{{ node_fqdn }}.pem"
      salt.minion_pub = "/srv/vagrant/{{ cluster_name }}/salt/minion_keys/{{ node_fqdn }}.pub"
    end

    {%- endif %}
  
  end
  {%- endfor %}

end
  